VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "ferret" do |t|
  end

  config.vm.synced_folder "../home", "/ferret"

  config.vm.box = "hashicorp/precise64"
  config.vm.hostname = "vagrant"

  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.network "forwarded_port", guest: 8080, host: 18080

  config.vm.provision :shell, :path => "upgrade_puppet.sh"
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = "modules"
    puppet.manifest_file  = "site.pp"
    puppet.options << '--fileserverconfig /vagrant/filesserver.conf'
  end

  config.vm.provision "shell", inline: "touch ~/.hushlogin"

end
